module.exports = {
  corePlugins: {
    appearance: false,
    accessibility: false,
    boxShadow: false,
    borderCollapse: false,
    backgroundSize: false,
    backgroundAttachment: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    tableLayout: false,
    tracking: false,
    translate: false,
    transitionProperty: false,
    transitionDuration: false,
    transitionTimingFunction: false,
    fill: false,
    float: false,
    stroke: false,
    skew: false,
    scale: false,
    select: false,
    clear: false,
    opacity: false,
    objectPosition: false,
    objectFit: false,
    pointer: false,
    pointerEvents: false,
    resize: false,
    rotate: false,
    userSelect: false,
  },
  theme: {
    colors: {
      white: '#ffffff',
      terminalGray: '#2D3748',
      terminalGreen: '#68D391',
      red: '#E53E3E',
      yellow: '#F6E05E',
      teal: {
        800: '#285E61',
        400: '#4FD1C5',
      },
    },
    screens: {
      sm: { max: '639px' },
      xsm: { max: '320px' },
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
    fontFamily: {
      heading: ['Courier Prime'],
    },
  },
  variants: {},
  plugins: [],
};
